### PR TITLE
Rollup PIA to use shared package

### PR DESCRIPTION
**Pull request by Alixers505**
https://www.pivotaltracker.com/story/show/171677237

### CODE REVIEW

**Comment by zarathustra323** [comment]
@Alixers505 this was setup very similar to the other dental sites (which I'm sure was the intention). However, PIA's current site is not set up this way. It's still using 300x600's (even though they don't appear to be display) and the "standard" card-deck / list load more.

Can you verify with Deb whether PIA should be changed to be like the other dental sites?

**Comment by Alixers505** [comment]
Rebased branch and resolved conflict

**Comment by zarathustra323** [comment]
@Alixers505 there's still some issues with this PR history... there shouldn't be 40,000+ deletions.

Can you try to rebase it again? If it's too messed up, you might have to close and start over :/

**Comment by Alixers505** [comment]
Rebased again and there are 51 unresolved conflicts now... Closing this thing out. I guess I'll have to do it all all over again :(

**Pull request closed without merging**
